version: '3.7'
services:
  home-assistant:
    restart: always
    container_name: hal
    image: homeassistant/home-assistant:0.112.2
    environment:
      - TZ=Europe/Rome
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ${PWD}/etc:/config
    network_mode: host
    labels:
      # Datadog Agent Autodiscovery for Logs
      - "com.datadoghq.ad.logs=[{\"source\": \"home-assistant\", \"service\": \"hal\"}]"
