version: 2.1
commands:
  run-tox:
    parameters:
      env:
        description: Tox environment
        type: string
    steps:
      # Install test dependencies and parametrize tox execution
      - checkout
      - run: sudo pip install tox codecov
      - run: tox -e << parameters.env >> && codecov

jobs:
  test-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - run-tox:
          env: "py37"
  lint:
    docker:
      - image: circleci/python:latest
    steps:
      - run-tox:
          env: "lint"
workflows:
  version: 2
  build:
    jobs:
      - test-py37
      - lint
