- id: '1585440144639'
  alias: Turn on entryway lights
  description: Enable all the lights when the button is pressed, unless a light is
    already turned on.
  trigger:
  - entity_id: light.entryway
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'off'
  - condition: state
    entity_id: light.tv_backlight
    state: 'off'
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  action:
  - data: {}
    entity_id: light.entryway
    service: light.turn_on
  - data: {}
    entity_id: light.living_room
    service: light.turn_on
  - data: {}
    entity_id: light.kitchen
    service: light.turn_on
  - data: {}
    entity_id: light.tv_backlight
    service: light.turn_off
- id: '1586690764601'
  alias: Heat Bathrooms
  description: Heat bathrooms for 20 minutes.
  trigger:
  - entity_id: input_boolean.bathroom_heating
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: climate.tado_smart_thermostat_ru1111297536
    service: climate.turn_on
  - data:
      hvac_mode: heat
      temperature: 24
    entity_id: climate.tado_smart_thermostat_ru1111297536
    service: climate.set_temperature
  - delay: 00:20:00
  - data:
      temperature: 5
    entity_id: climate.tado_smart_thermostat_ru1111297536
    service: climate.set_temperature
  - data: {}
    entity_id: climate.tado_smart_thermostat_ru1111297536
    service: climate.turn_off
  - data: {}
    entity_id: input_boolean.bathroom_heating
    service: input_boolean.turn_off
