# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  name: Home
  unit_system: metric
  time_zone: Europe/Rome
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

zone: !include zones.yaml

# Text to speech
tts:
  - platform: google_translate

# Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  service_account: !include google/service_account.json
  report_state: true
  exposed_domains:
    - light
    - climate
    - scene

# KNX Integration
knx: !include integrations/knx.yaml
light: !include integrations/knx_lights.yaml

# Device Trackers
device_tracker:
  - platform: ping
    hosts: !include hosts.yaml

# Export Data
datadog:
  host: localhost
  port: 8125
  prefix: testing.hal
