# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  name: Home
  unit_system: metric
  time_zone: Europe/Rome
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

zone: !include zones.yaml

# Text to speech
tts:
  - platform: google_translate

# Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Alexa
alexa:
  smart_home:
    locale: it-IT
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_domains:
        - climate
        - input_boolean
        - light
        - scene

# KNX Integration
knx: !include integrations/knx.yaml
light: !include integrations/knx_lights.yaml

# Device Trackers
device_tracker:
  - platform: ping
    hosts: !include hosts.yaml

# Export Data
datadog:
  host: localhost
  port: 8125
  prefix: testing.hal
