name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  hal-config-check:
    runs-on: ubuntu-latest

    container:
      image: python:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant

      - name: Create dummy secrets
        run: |
          touch hass/etc/customize.yaml
          touch hass/etc/hosts.yaml
          touch hass/etc/zones.yaml
          echo 'knx_ip: 10.0.0.1' >> hass/etc/secrets.yaml
          echo 'local_ip: 10.0.0.1' >> hass/etc/secrets.yaml
          echo 'home_latitude: 42.0' >> hass/etc/secrets.yaml
          echo 'home_longitude: 42.0' >> hass/etc/secrets.yaml
          echo 'home_elevation: 42' >> hass/etc/secrets.yaml
      
      - name: Check configuration
        run: hass -c hass/etc/ --script check_config
