name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  hal-config-check:
    runs-on: ubuntu-latest

    container:
      image: python:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant

      - name: Create dummy secrets
        run: |
          mkdir hass/etc/google/
          echo 'google_project_id: dummy' >> hass/etc/secrets.yaml
          echo 'knx_ip: 10.0.0.1' >> hass/etc/secrets.yaml
          echo 'local_ip: 10.0.0.1' >> hass/etc/secrets.yaml
          echo '{"client_email": "dummy@account.com", "private_key": "secret"}' > hass/etc/google/service_account.json
      
      - name: Check configuration
        run: hass -c hass/etc/ --script check_config
